### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by dustdfg** [ARKANYOTA/globs#3]
What is the license?

**Comment by Yolwoocle** [comment]
Hey! By default, if a repo does not contain a license, it is "All rights reserved". This means that even though the code is publicly available, you cannot modify, or distribute the code without our consent (this is called "[source available](https://en.wikipedia.org/wiki/Source-available_software)" as opposed to "[open source](https://en.wikipedia.org/wiki/Open_source)"). We did this as right now we don't know what license we should put, and it is very common for Web games to be stolen and put on others websites without their creators' consent (happened to me a few times already).

We might add a license down the line, as I believe it would be cool to allow to modify and reuse parts of the game, but every bit of freedom we give to honest people is an avenue for abuse. On the meantime, do you want to do anything particular with the source code? I am very lax with what people can do with it, I just want to be careful. If you want to use snippets of code or small bits of artwork, you can feel free to. Otherwise, you can contact me on Discord (`@yolwoocle`) if you wish.

**Comment by Yolwoocle** [comment]
Update: I added more info regarding the lack of a license in the README.md file.
